# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'ActivityTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Messaging'
  
end
